name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  analyzer: 5.3.1

dependencies:
  db:
    path: ../db

  freezed_annotation: ^3.1.0
  json_annotation: 4.9.0

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.9.0
  lints: ^6.0.0

