name: db
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  stormberry: 0.16.0

dev_dependencies:
  build_runner: 2.5.4
  lints: 6.0.0
  test: 1.26.3
